services:
  devcontainer:
    build:
      args:
        USERNAME: ${USERNAME}
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      cache_from:
        - type=local,src=../${COMPOSE_PROJECT_NAME}.cache
      cache_to:
        - type=local,dest=../${COMPOSE_PROJECT_NAME}.cache,mode=max
      context: .
    command: sleep infinity
    post_start:
      - command: dotfiles_hook
    pull_policy: never
    user: ${USERNAME}
    volumes:
      - type: bind
        source: ..
        target: /workspaces/${COMPOSE_PROJECT_NAME}
      - type: volume
        source: dotfiles
        target: /home/${USERNAME}/dotfiles

volumes:
  dotfiles:
